### ISSUE TITLE
NPE on logger name from SLF4J via Netty.

### ISSUE THREAD

**Issue by KyleU** [outr/scribe#12]
First off, thanks again for this library, it's been tremendous, filling a gap in Scala.js.

I've been able to get everything working, but when I reference postgres-async, which is built on netty, I get the following stack trace:

```
Caused by: java.lang.NullPointerException: name
	at io.netty.util.internal.logging.AbstractInternalLogger.<init>(AbstractInternalLogger.java:41)
	at io.netty.util.internal.logging.Slf4JLogger.<init>(Slf4JLogger.java:30)
	at io.netty.util.internal.logging.Slf4JLoggerFactory.newInstance(Slf4JLoggerFactory.java:73)
	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:97)
	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:90)
	at io.netty.channel.MultithreadEventLoopGroup.<clinit>(MultithreadEventLoopGroup.java:34)
	at com.github.mauricio.async.db.util.NettyUtils$.DefaultEventLoopGroup$lzycompute(NettyUtils.scala:24)
	at com.github.mauricio.async.db.util.NettyUtils$.DefaultEventLoopGroup(NettyUtils.scala:24)
	at com.github.mauricio.async.db.postgresql.pool.PostgreSQLConnectionFactory$.$lessinit$greater$default$2(PostgreSQLConnectionFactory.scala:47)
	at services.database.Database$.open(Database.scala:33)
```

You can clone the `scribe` branch from https://github.com/KyleU/boilerplay/tree/scribe to test this. As is, the application runs fine, but uncommenting `Database.open` from https://github.com/KyleU/boilerplay/blob/scribe/app/util/Application.scala#L60 causes the above stack trace.

Attaching a debugger shows that the name isn't provided. Is this something netty should fix, or is there a way to fix it in scribe?

**Comment by darkfrog26** [comment]
I'm looking into this, but what I don't see is any reference to Scribe here.  If you remove the Scribe dependency does the error go away?

**Comment by darkfrog26** [comment]
Looks like `InternalLoggerFactory:90` is the culprit.  Oddly, it would seem when it calls `clazz.getName()` on whatever class it is, it returns `null`.

**Comment by darkfrog26** [comment]
@KyleU any chance you can create a more concise example representing this issue?

**Comment by KyleU** [comment]
Sorry for the delay, thought I'd replied. I went ahead and used Scribe for all my Scala.js logging, and am keeping logback for the server. Thanks for looking at this.

**Comment by darkfrog26** [comment]
If you're willing, I'd still like your help resolving this so Scribe can be useful on the JVM? ;)

**Comment by KyleU** [comment]
Ok, it looks like the problem was netty, as you suspected. upgrading the netty version fixed the issue, I guess I just didn't run into it before attempting to integrate Scribe. Sorry for the bogus report, thanks for working on it -  I love the library, by the way.

**Comment by darkfrog26** [comment]
Great, I'm glad you were able to get it figured out.  Feel free to let me know if you have any feature requests or suggestions.
