### ISSUE TITLE
Deadlocks

### ISSUE THREAD

**Issue by andreak** [outr/scribe#131]
Hi, we're experiencing lots of deadlocks using Scribe (version 2.7.12, using Scala-2.12.12).
examples:
```
"ajp-nio-8089-exec-3" #137 daemon prio=5 os_prio=0 cpu=14.76ms elapsed=486.89s tid=0x00007ff188006800 nid=0x943 waiting for monitor entry  [0x00007ff178ce4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at scribe.handler.SynchronousLogHandler.log(SynchronousLogHandler.scala:18)
	- waiting to lock <0x00000000827c9540> (a scribe.handler.SynchronousLogHandler)
	at scribe.Logger.$anonfun$log$4(Logger.scala:41)
	at scribe.Logger.$anonfun$log$4$adapted(Logger.scala:41)
	at scribe.Logger$$Lambda$165/0x0000000100370040.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scribe.Logger.$anonfun$log$3(Logger.scala:41)
	at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
	at scribe.Logger$$Lambda$164/0x000000010036f040.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at scribe.Logger.log(Logger.scala:40)
	at scribe.Logger.$anonfun$log$6(Logger.scala:42)
	at scribe.Logger.$anonfun$log$6$adapted(Logger.scala:42)
	at scribe.Logger$$Lambda$167/0x0000000100371840.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at scribe.Logger.$anonfun$log$3(Logger.scala:42)
	at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
	at scribe.Logger$$Lambda$164/0x000000010036f040.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at scribe.Logger.log(Logger.scala:40)
	at scribe.slf4j.ScribeLoggerAdapter.log(ScribeLoggerAdapter.scala:31)
	at scribe.slf4j.ScribeLoggerAdapter.trace(ScribeLoggerAdapter.scala:46)
	at org.apache.commons.logging.LogAdapter$Slf4jLog.trace(LogAdapter.java:387)
```
```
"pool-5-thread-4":
        at scribe.handler.SynchronousLogHandler.log(SynchronousLogHandler.scala:18)
        - waiting to lock <0x00000007429e8130> (a scribe.handler.SynchronousLogHandler)
        at scribe.Logger.$anonfun$log$4(Logger.scala:41)
        at scribe.Logger.$anonfun$log$4$adapted(Logger.scala:41)
        at scribe.Logger$$Lambda$165/0x0000000800370040.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scribe.Logger.$anonfun$log$3(Logger.scala:41)
        at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
        at scribe.Logger$$Lambda$164/0x000000080036f040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.Logger.log(Logger.scala:40)
        at scribe.Logger.$anonfun$log$6(Logger.scala:42)
        at scribe.Logger.$anonfun$log$6$adapted(Logger.scala:42)
        at scribe.Logger$$Lambda$167/0x0000000800371840.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.Logger.$anonfun$log$3(Logger.scala:42)
        at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
        at scribe.Logger$$Lambda$164/0x000000080036f040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.Logger.log(Logger.scala:40)
        at scribe.slf4j.ScribeLoggerAdapter.log(ScribeLoggerAdapter.scala:31)
        at scribe.slf4j.ScribeLoggerAdapter.info(ScribeLoggerAdapter.scala:78)
        at org.apache.commons.logging.impl.SLF4JLog.info(SLF4JLog.java:152)
        at org.springframework.aop.aspectj.AspectJWeaverMessageHandler.handleMessage(AspectJWeaverMessageHandler.java:62)
        at org.aspectj.weaver.tools.WeavingAdaptor$WeavingAdaptorMessageHolder.handleMessage(WeavingAdaptor.java:766)
```

I have full stack-traces but would rather not share them in public....

Any hints on what may cause this?

**Comment by darkfrog26** [comment]
Please check this in `2.8.3` and see if it is resolved.

**Comment by andreak** [comment]
No deadlocks so far, and they used to come "by now". Closing issue for now.

**Comment by darkfrog26** [comment]
@andreak awesome! Good to hear. Please let me know if you have any other issues.
