### ISSUE TITLE
Deadlock in ConsoleWriter.scala:14

### ISSUE THREAD

**Issue by andreak** [outr/scribe#132]
We're now getting deadlocks when logging ERROR, which goes to console as well as to file.

```
Found one Java-level deadlock:
=============================
"localhost-startStop-1":
  waiting to lock monitor 0x00007fc34004fa80 (object 0x0000000742663710, a scribe.writer.ConsoleWriter$),
  which is held by "pool-2-thread-16"
"pool-2-thread-16":
  waiting to lock monitor 0x00007fc348006680 (object 0x0000000741e798a8, a org.apache.catalina.loader.ParallelWebappClassLoader),
  which is held by "localhost-startStop-1"

Java stack information for the threads listed above:
===================================================
"localhost-startStop-1":
        at scribe.writer.ConsoleWriter$.write(ConsoleWriter.scala:14)
        - waiting to lock <0x0000000742663710> (a scribe.writer.ConsoleWriter$)
        at scribe.handler.SynchronousLogHandler$.$anonfun$log$3(SynchronousLogHandler.scala:27)
        at scribe.handler.SynchronousLogHandler$.$anonfun$log$3$adapted(SynchronousLogHandler.scala:25)
        at scribe.handler.SynchronousLogHandler$$$Lambda$171/0x0000000800376040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.handler.SynchronousLogHandler$.log(SynchronousLogHandler.scala:25)
        at scribe.handler.SynchronousLogHandler.log(SynchronousLogHandler.scala:18)
        at scribe.Logger.$anonfun$log$4(Logger.scala:72)
        at scribe.Logger.$anonfun$log$4$adapted(Logger.scala:72)
        at scribe.Logger$$Lambda$164/0x0000000800370840.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scribe.Logger.$anonfun$log$3(Logger.scala:72)
        at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:71)
        at scribe.Logger$$Lambda$163/0x0000000800370040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.Logger.log(Logger.scala:71)
        at scribe.Logger.$anonfun$log$6(Logger.scala:73)
        at scribe.Logger.$anonfun$log$6$adapted(Logger.scala:73)
        at scribe.Logger$$Lambda$166/0x0000000800372040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.Logger.$anonfun$log$3(Logger.scala:73)
        at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:71)
        at scribe.Logger$$Lambda$163/0x0000000800370040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:407)
        at scribe.Logger.log(Logger.scala:71)
```

**Comment by darkfrog26** [comment]
This should be fixed with `3.0.1`. Please let me know if it still happens.
