### ISSUE TITLE
Scribe chokes in both SBT and the IntelliJ console due to believing there's not enough columns

### ISSUE THREAD

**Issue by s5bug** [outr/scribe#361]
With default settings, <https://github.com/outr/scribe/blob/3.10.4/core/shared/src/main/scala/scribe/format/FormatBlock.scala#L306> reports `pre` as being `"    "` (length 4, I have used Non-breaking Spaces to prevent GitHub from flattening the whitespace but in reality these are normal U+0020 spaces), and `max` as being `-3`, causing a `StringIndexOutOfBoundsException` on L313.

By debugger, <https://github.com/outr/scribe/blob/3.10.4/core/jvm/src/main/scala/scribe/Platform.scala#L47>'s `getColumns` is returning `0`, leading to `tputColumns` being called, which reports `1`, but only in IntelliJ's Run window.

In IntelliJ's terminal, `tputColumns` would produce the correct result, even on Windows:

![image](https://user-images.githubusercontent.com/7751296/202435106-600b484c-67a1-4825-87b5-e04e9ff6d693.png)

**Comment by s5bug** [comment]
The issue also occurs any time the application is being run from SBT, whether it's from IntelliJ or externally. Before the stack trace is printed, a few warnings are given:
```
[error] Nov 17, 2022 3:54:46 AM org.jline.utils.Log logr
[error] WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```
<details>
<summary>Full stack trace</summary>

```
[error] java.lang.StringIndexOutOfBoundsException: begin 0, end -3, length 56
[error]         at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
[error]         at java.base/java.lang.String.substring(String.java:2707)
[error]         at scribe.output.TextOutput$.splitAt$extension(LogOutput.scala:32)
[error]         at scribe.output.TextOutput.splitAt(LogOutput.scala:32)
[error]         at scribe.format.FormatBlock$MultiLine.$anonfun$format$11(FormatBlock.scala:313)
[error]         at scala.collection.immutable.List.flatMap(List.scala:293)
[error]         at scribe.format.FormatBlock$MultiLine.format(FormatBlock.scala:309)
[error]         at scribe.format.FormatBlocksFormatter.$anonfun$format$1(FormatBlocksFormatter.scala:8)
[error]         at scala.collection.immutable.List.map(List.scala:250)
[error]         at scribe.format.FormatBlocksFormatter.format(FormatBlocksFormatter.scala:8)
[error]         at scribe.handler.SynchronousLogHandle$.$anonfun$log$1(SynchronousLogHandle.scala:8)
[error]         at scribe.handler.SynchronousLogHandle$.$anonfun$log$1$adapted(SynchronousLogHandle.scala:7)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.handler.SynchronousLogHandle$.log(SynchronousLogHandle.scala:7)
[error]         at scribe.handler.LogHandlerBuilder.log(LogHandlerBuilder.scala:14)
[error]         at scribe.Logger.$anonfun$logInternal$2(Logger.scala:131)
[error]         at scribe.Logger.$anonfun$logInternal$2$adapted(Logger.scala:131)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at scribe.Logger.$anonfun$logInternal$1(Logger.scala:131)
[error]         at scribe.Logger.$anonfun$logInternal$1$adapted(Logger.scala:130)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.logInternal(Logger.scala:130)
[error]         at scribe.Logger.$anonfun$logInternal$4(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$4$adapted(Logger.scala:132)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.$anonfun$logInternal$1(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$1$adapted(Logger.scala:130)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.logInternal(Logger.scala:130)
[error]         at scribe.Logger.$anonfun$logInternal$4(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$4$adapted(Logger.scala:132)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.$anonfun$logInternal$1(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$1$adapted(Logger.scala:130)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.logInternal(Logger.scala:130)
[error]         at scribe.Logger.$anonfun$logInternal$4(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$4$adapted(Logger.scala:132)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.$anonfun$logInternal$1(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$1$adapted(Logger.scala:130)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.logInternal(Logger.scala:130)
[error]         at scribe.Logger.$anonfun$logInternal$4(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$4$adapted(Logger.scala:132)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.$anonfun$logInternal$1(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$1$adapted(Logger.scala:130)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.logInternal(Logger.scala:130)
[error]         at scribe.Logger.$anonfun$logInternal$4(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$4$adapted(Logger.scala:132)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.$anonfun$logInternal$1(Logger.scala:132)
[error]         at scribe.Logger.$anonfun$logInternal$1$adapted(Logger.scala:130)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at scribe.Logger.logInternal(Logger.scala:130)
[error]         at scribe.Logger.log(Logger.scala:119)
[error]         at scribe.ScribeImpl$.$anonfun$log$extension$1(ScribeImpl.scala:9)
[error]         at delay @ scribe.ScribeImpl$.log$extension(ScribeImpl.scala:9)
[error]         at defer @ scribe.ScribeImpl$.log$extension(ScribeImpl.scala:13)
[error]         at defer @ scribe.ScribeImpl$.log$extension(ScribeImpl.scala:13)
```

</details>

**Comment by darkfrog26** [comment]
Also, would you rather, when not able to be detected, I set a default like 120 characters or do I think I just just disable alignment?

**Comment by darkfrog26** [comment]
Here's what I'm thinking:
- Detect rows (currently adding this for some new features) and columns
- If columns is less than `minimumColumns` (defaults to 10), the column count will be set to `maximumColumns` (defaults to 5000 to essentially disable breaking)
Any thoughts?

**Comment by darkfrog26** [comment]
See: https://github.com/outr/scribe/blob/master/core/jvm/src/main/scala/scribe/Platform.scala#L13-L17

**Comment by s5bug** [comment]
I am in favor of your proposed behavior! I don't know why tput is reporting 1...

**Comment by s5bug** [comment]
I _would_ prefer Scribe not pollute my home directory, instead opting for a cache directory:  <https://github.com/outr/scribe/blob/master/core/jvm/src/main/scala/scribe/Platform.scala#L90>. `XDG_CACHE_HOME` on systems that support it, `%LocalAppData%/scribe` on Windows, etc. Especially since it can recreate the file.

**Comment by darkfrog26** [comment]
New release with these changes: https://github.com/outr/scribe/releases/tag/3.10.5

**Comment by s5bug** [comment]
It does work!

**Comment by s5bug** [comment]
As for caches, perhaps it's worth making something that looks for `{XDG_CACHE_HOME}/scribe` on Linux, `{CSIDL_LOCAL_APPDATA}/scribe` on Windows. Mac seems to not have an environment variable and `{user.home}/Library/Caches/com.outr.scribe` is fine.

A good fallback for `{XDG_CACHE_HOME}` is `{user.home}`. Getting `{CSIDL_LOCAL_APPDATA}` should _always_ succeed, but I think a bit native code might have to be written to do it?

**Comment by darkfrog26** [comment]
If you'd be interested in testing this out I'd welcome a PR for the functionality. :)
